# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coddy', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
