# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coddy', '0005_auto_20180317_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='sms',
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 3, 27, 17, 10, 35, 122720)),
        ),
        migrations.AlterField(
            model_name='vol',
            name='image',
            field=models.ImageField(upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 3, 27, 17, 10, 35, 122720)),
        ),
    ]
