# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coddy', '0006_auto_20180327_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/img')),
                ('disc', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 3, 28, 12, 29, 51, 271395)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 3, 28, 12, 29, 51, 271853)),
        ),
    ]
